spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batdongsan
    username: root
    password: haicr147258369
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: hai_2151220168@dau.edu.vn
    password: hsemhjwecwhuhndf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  

openai:
  api:
    key: "sk-cuStzQbInY9aFkK8iUvo89Coq4EybQ5pgIvMbFx5Krb2ge"
    base-url: "https://v98store.com/v1"
  model: "gpt-4o-mini"